export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as PostDetails } from './PostDetails';
export { default as CreatePost } from './CreatePost';
export { default as Profile } from './Profile';
export { default as AdminPanel } from './AdminPanel';
export { default as MyPosts } from './MyPosts';
export { default as Favorites } from './Favorites';